theme:
  name: material
  features:
    - search.suggest
    - search.share
    - toc.follow
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.indexes
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tabs.link

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.keys
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes


extra_javascript:
  - https://mkdocs.twango.dev/javascripts/mathjax.js
  - https://mkdocs.twango.dev/javascripts/kotlin.js
  - https://mkdocs.twango.dev/javascripts/kotlin-playground.js
  - https://mkdocs.twango.dev/javascripts/polyfill.js
  - https://mkdocs.twango.dev/javascripts/tex.js
  - https://mkdocs.twango.dev/javascripts/vega.js
  - https://mkdocs.twango.dev/javascripts/vega-lite.js
  - https://mkdocs.twango.dev/javascripts/vega-embed.js

extra_css:
  - https://mkdocs.twango.dev/css/kotlin.css
  - https://mkdocs.twango.dev/css/katex.css
